#! /usr/bin/env bash

set -Eeuo pipefail

gh_url="https://github.com/remmelt"

my_dir="$(dirname "${BASH_SOURCE[0]}")"
default_branch="$("$my_dir"/github-default-branch)"

branch_name=$(git rev-parse --abbrev-ref HEAD)
repo_name=$(basename "$(git rev-parse --show-toplevel)")

git push origin "$branch_name" --force-with-lease

url="$gh_url/$repo_name/compare/$default_branch...$branch_name"

open "$url"
